#!/bin/sh
echo "🚫 Prevent push of .github/workflows"
if git diff --cached --name-only | grep -q '.github/workflows'; then
  echo "❌ No puedes pushear workflows directamente. Usa ./deploy_workflows.sh"
  exit 1
fi
