name: 🚀 Deploy MkDocs to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - documentation
      - release
      - gh-pages
      - main
    # paths:
    #   - 'docs/**'
    #   - 'mkdocs.yml'
    #   - 'index.md'

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write
  issues: write
  checks: write
  statuses: write
  deployments: write
  actions: write
  repository-projects: write
  discussions: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material pyyaml
          pip install -r requirements.txt

      - name: 🧠 Autogenerar navegación MkDocs semántica
        run: python scripts/generate_mkdocs_semantic.py
        
      # - name: Validar configuración de MkDocs
      #   run: |
      #     mkdocs build --strict --site-dir /tmp/mkdocs_build_check

      - name: Build and deploy
        run: |
          mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: false
          MKDOCS_SITE_DIR: docs
          MKDOCS_SITE_NAME: ATLANTYDE LABs Foundation
          MKDOCS_REPO_BRANCH: gh-pages
